FROM oven/bun:latest AS builder
WORKDIR /app
COPY . .
RUN bun install
RUN bun build ./server.ts --outdir ./dist --target bun

FROM oven/bun:latest
WORKDIR /app
COPY --from=builder /app/dist .
COPY karar_başlık.png ./
COPY .env .

USER bun 
EXPOSE 5000
ENTRYPOINT [ "bun" ]
CMD [ "run","server.js" ]


#compile ----------------

#stage 1
# FROM oven/bun:1.3 AS builder
# WORKDIR /app
# COPY . .
# RUN bun install 
# RUN bun build ./server.ts --target bun --compile

# #stage 2
# FROM oven/bun:1.3
# WORKDIR /app
# COPY karar_başlık.png ./
# COPY .env .
# COPY --from=builder /app/server /app

# USER bun 
# EXPOSE 5000
# ENTRYPOINT [ "./server" ]

# # CMD [ "run","./server" ]

