#stage 1
FROM oven/bun:1.3 AS builder

WORKDIR /app

COPY . .
RUN bun install
RUN bun build ./server.ts --outdir ./dist --target bun


#stage 2
FROM oven/bun:1.3
WORKDIR /app
COPY karar_başlık.png ./
COPY .env ./
COPY --from=builder /app/dist /app/dist

# oven/bun ile hazır gelen bir user kullanıcı rolu
USER bun 

EXPOSE 5000

ENTRYPOINT [ "bun" ]

CMD [ "run","dist/server.js" ]

